permalink:   none
lsi:         false
destination: public
kramdown:
  auto_ids:  false
  syntax_highlighter_opts:
    disable: true
exclude:
  - Readme.md
  - bin
  - script
  - vendor
  - Gemfile

theme: jekyll-theme-cayman